### ISSUE TITLE
Criar o extensor para 32bits

### ISSUE THREAD

**Issue by brenoamin** [brenoamin/plataforma-jogos-laboratorio-iv#12]
Módulo deve ser parametrizável e deve complentar valores em complemento de 2 para um tamanho de 32 bits

![Image](https://github.com/brenoamin/plataforma-jogos-laboratorio-iv/assets/18634201/c9d27cf5-d35f-4d8e-8ddb-ff4d7ca76574)

Entradas:
- INSTR

Saída:
- Ext_immediate

**Comment by brenoamin** [comment]
This issue was addressed by the creation of the[ extensor module](https://github.com/brenoamin/plataforma-jogos-laboratorio-iv/tree/main/modulo_processor/src/extensor).

**Comment by taffarel55** [comment]
Falta o testbench, ele estava com um problema

**Comment by taffarel55** [comment]
@brenoamin @GeraldinJr

**Comment by brenoamin** [comment]
Agora sim. @GeraldinJr consertou o testbench
