### ISSUE TITLE
Alinhar arquitetura com todo o time

### ISSUE THREAD

**Issue by taffarel55** [brenoamin/plataforma-jogos-laboratorio-iv#14]
@brenoamin @GeraldinJr @isaacpcaraujo @ofabiobraga @henriqsp, leo

E ai pessoal, ainda temos bastante coisa para fazer. Vamos tentar pegar as tarefas e tocar!

**Comment by brenoamin** [comment]
Acho que podemos fechar essa discussão aqui.

O alinhamento já foi realizado e as tasks já estão no board.
