### ISSUE TITLE
Criar memória de programa

### ISSUE THREAD

**Issue by taffarel55** [brenoamin/plataforma-jogos-laboratorio-iv#8]
- Criar uma memória 32x32k para armazenar instruções
- Criar testbench

![Image](https://github.com/brenoamin/brenoamin/assets/18634201/87ad67b2-1bd5-4b25-b571-ce22f242c134)

Entradas:
- ADDR

Saídas:
- DATA

**Comment by taffarel55** [comment]
@brenoamin Acredito que já esteja finalizada, talvez só faltaria o testbench individual a partir de um arquivo carregando direto na memória, mas já tem uma forma melhor de se fazer isso passando o arquivo como parâmetro.

**Comment by brenoamin** [comment]
Perfeito, vou mover para Done 👍 🔥
